# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('profile', models.URLField()),
                ('avatar_small', models.URLField()),
                ('avatar_medium', models.URLField()),
                ('avatar_large', models.URLField()),
                ('state', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Busy'), (3, 'Away'), (4, 'Snooze'), (5, 'Looking to trade'), (6, 'Looking to play')], default=0)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
    ]
